name: deploy docker image

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build and deploy docker image
        env:
          DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
        run: ./gradlew bootBuildImage
